# Generated by Django 5.0 on 2023-12-07 14:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(blank=True, max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(blank=True, max_length=30, verbose_name='sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='cpf')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_verified', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_user_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.customuser')),
                ('foto', models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.customuser',),
        ),
        migrations.CreateModel(
            name='ItemOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='usuarios.opcao')),
            ],
        ),
        migrations.AddField(
            model_name='opcao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='usuarios.produto'),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.customuser')),
                ('foto', models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/')),
                ('produtos', models.ManyToManyField(blank=True, to='usuarios.produto')),
            ],
            options={
                'abstract': False,
            },
            bases=('usuarios.customuser',),
        ),
    ]
