# Generated by Django 5.0 on 2023-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='produtos',
        ),
    ]
