# Generated by Django 5.0 on 2023-12-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='usuarios.produto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='loja',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, related_name='lojas', to='usuarios.categoria'),
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.loja')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoComplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('preco_adicional', models.DecimalField(decimal_places=2, max_digits=6)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='usuarios.complemento')),
            ],
        ),
    ]
