# Generated by Django 5.0 on 2023-12-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_categoria_loja_produtos_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcaocomplemento',
            name='complemento',
        ),
        migrations.AlterField(
            model_name='loja',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.produto'),
        ),
        migrations.DeleteModel(
            name='Complemento',
        ),
        migrations.DeleteModel(
            name='OpcaoComplemento',
        ),
    ]
