# Generated by Django 5.0 on 2023-12-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_loja_categorias_alter_loja_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
