# Generated by Django 5.0 on 2023-12-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_customuser_sobrenome_alter_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='nomeLoja',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
