# Generated by Django 5.0 on 2024-01-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_cep_cidade_estado_bairro_endereco_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_poups',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
