# Generated by Django 5.0 on 2024-01-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_loja_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.loja'),
        ),
    ]
