# Generated by Django 5.0 on 2024-01-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_produto_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
