# Generated by Django 5.0 on 2024-01-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_loja_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
