# Generated by Django 5.0 on 2024-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='foto',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='itemopcao',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itemopcao',
            name='foto',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='opcao',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='opcao',
            name='foto',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
