# Generated by Django 5.0 on 2024-01-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_categoria_foto_alter_loja_valor_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='capa',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
    ]
