# Generated by Django 5.0 on 2024-03-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_loja_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SubCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='subclientes_fotos/')),
                ('cliente_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subperfis', to='usuarios.cliente')),
            ],
        ),
    ]
