# Generated by Django 5.0 on 2024-03-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_cliente_pontos_subcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plano_familia',
            field=models.BooleanField(default=False, verbose_name='Plano Família'),
        ),
        migrations.CreateModel(
            name='Subperfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='subclientes_fotos/')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subperfis', to='usuarios.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='SubCliente',
        ),
    ]
