# Generated by Django 5.0 on 2024-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_cliente_plano_familia_subperfil_delete_subcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email_pagseguro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='token_pagseguro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
