# Generated by Django 5.0 on 2024-03-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_loja_email_pagseguro_loja_token_pagseguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='nomeDono',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
