# Generated by Django 5.0 on 2024-03-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_remove_loja_nomedono'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pontos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
