# Generated by Django 5.0 on 2024-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_produto_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ever_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=99999999999, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=99999999999, null=True),
        ),
    ]
