# Generated by Django 5.0.4 on 2024-05-28 16:04

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_produto_pontos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('loja_id', models.IntegerField()),
                ('cliente_id', models.IntegerField()),
                ('correlation_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loja',
            name='ever_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='stripe_payout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subperfil',
            name='is_titular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=400, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='none', max_length=50)),
                ('pagamento', models.CharField(default='none', max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.loja')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.PositiveIntegerField()),
                ('imagem', models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/')),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='usuarios.produto')),
            ],
        ),
        migrations.CreateModel(
            name='CompraAcumulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_comprada', models.PositiveIntegerField(default=0)),
                ('pontos_para_proxima_promocao', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.produto')),
                ('promocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.promocao')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='usuarios.promocao'),
        ),
        migrations.CreateModel(
            name='TokenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=10)),
                ('expiracao', models.DateTimeField(default=usuarios.models.default_expiration_date)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido')),
            ],
        ),
    ]
