# Generated by Django 5.0 on 2024-04-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_loja_ever_saldo_loja_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
