# Generated by Django 5.0.4 on 2024-05-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_alter_loja_capa_alter_loja_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='foto',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='images/user_2.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='itemopcao',
            name='foto',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='opcao',
            name='foto',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, default='/images/ella-olsson-oPBjWBCcAEo-unsplash_1.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subperfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='images/user_2.png', null=True, upload_to='subclientes_fotos/'),
        ),
    ]
