# Generated by Django 5.0 on 2024-04-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_loja_is_active_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='localizao',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
