# Generated by Django 5.0.4 on 2024-05-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_alter_categoria_foto_alter_categoriaproduto_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
