# Generated by Django 5.0 on 2024-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_pedido_data_pedido_localizao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
