# Generated by Django 5.0.4 on 2024-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_alter_charge_correlation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
