# Generated by Django 5.0 on 2024-04-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_pedido_confirmado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='preco',
            new_name='total',
        ),
    ]
