# Generated by Django 5.0.4 on 2024-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_alter_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retirada_na_loja',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
