# Generated by Django 5.0.4 on 2024-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_pedido_retirada_na_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='retirada_na_loja',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
