# Generated by Django 5.0.4 on 2024-06-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_charge_retirada_na_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
