# Generated by Django 5.0 on 2024-04-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_alter_pedido_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='localizao',
            new_name='localizacao',
        ),
    ]
