# Generated by Django 5.0.4 on 2024-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_charge_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
