# Generated by Django 5.0.4 on 2024-06-04 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_pedido_correlation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_secreto',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
