# Generated by Django 5.0 on 2024-04-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
