# Generated by Django 5.0 on 2024-04-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_itempedido_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='foto',
        ),
    ]
