# Generated by Django 5.0.4 on 2024-05-09 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_remove_pedido_categoria_remove_pedido_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=10)),
                ('expiracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pedido')),
            ],
        ),
    ]
