# Generated by Django 5.0.4 on 2024-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_alter_pedido_codigo_secreto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_secreto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
