# Generated by Django 5.0.4 on 2024-05-11 18:38

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_tokenpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokenpedido',
            name='expiracao',
            field=models.DateTimeField(default=usuarios.models.default_expiration_date),
        ),
    ]
