# Generated by Django 5.0.4 on 2024-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_alter_pedido_codigo_secreto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
