# Generated by Django 5.0.4 on 2024-05-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_pedido_payment_id_alter_tokenpedido_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
