# Generated by Django 5.0.4 on 2024-06-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_lojafuncionario_loja_funcionarios'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lojafuncionario',
            unique_together={('loja', 'funcionario')},
        ),
    ]
