# Generated by Django 5.0.4 on 2024-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_remove_pedido_confirmado_pedido_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado',
            new_name='status',
        ),
    ]
