# Generated by Django 5.0.4 on 2024-05-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_rename_estado_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
