# Generated by Django 5.0.4 on 2024-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_alter_lojafuncionario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
