# Generated by Django 5.0.4 on 2024-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0045_pedido_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='tempo_entrega_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
