# Generated by Django 5.0.4 on 2024-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0046_loja_tempo_entrega_max_loja_tempo_entrega_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='subperfil',
            name='is_titular',
            field=models.BooleanField(default=False),
        ),
    ]
