# Generated by Django 5.0.4 on 2024-05-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_subperfil_is_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='stripe_payout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
