# Generated by Django 5.0.4 on 2024-05-21 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0049_compraacumulada_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraacumulada',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.promocao'),
        ),
    ]
