# Generated by Django 5.0.4 on 2024-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_compraacumulada_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, default='/images/unknown.png', null=True, upload_to='images/'),
        ),
    ]
