# Generated by Django 5.0.4 on 2024-05-21 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0051_promocao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='usuarios.promocao'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='usuarios.produto'),
        ),
    ]
