# Generated by Django 5.0.4 on 2024-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0052_produto_promocao_alter_promocao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraacumulada',
            name='pontos_para_proxima_promocao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
