# Generated by Django 5.0.4 on 2024-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0053_compraacumulada_pontos_para_proxima_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraacumulada',
            name='proxima_promocao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
