# Generated by Django 5.0.4 on 2024-05-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0054_compraacumulada_proxima_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraacumulada',
            name='proxima_promocao',
        ),
    ]
