# Generated by Django 5.0.4 on 2024-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0056_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
