# Generated by Django 5.0.4 on 2024-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0057_alter_charge_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charge',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
