# Generated by Django 5.0.4 on 2024-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0060_charge_correlation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='ever_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=999999, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=999999, null=True),
        ),
    ]
