# Generated by Django 5.0.4 on 2024-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0061_alter_loja_ever_saldo_alter_loja_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='ever_saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
    ]
